ishomme(yes,michaeljackson).
ishomme(yes,stephenharper).
ishomme(yes,mozart).
ishomme(yes,michelgagnon).
ishomme(non,blancheneige).
ishomme(yes,rafalnadal).
ishomme(yes,garfield).
ishomme(yes,micheldagenais).
ishomme(yes,johnlewis).
ishomme(yes,papefrancois).
ishomme(yes,jamesbond).
ishomme(non,juliesnyder).
ishomme(yes,moise).
ishomme(yes,mario).
ishomme(non,laracroft).
ishomme(non,jkrowling).
ishomme(yes,jacquesvilleneuve).
ishomme(non,cleopatre7).
ishomme(yes,victorhugo).
ishomme(yes,jesus).
ishomme(non,eugeniebouchard).
ishomme(yes,bradpitt).

isfictif(non,michaeljackson).
isfictif(non,stephenharper).
isfictif(non,mozart).
isfictif(non,michelgagnon).
isfictif(yes,blancheneige).
isfictif(non,rafalnadal).
isfictif(yes,garfield).
isfictif(non,micheldagenais).
isfictif(non,johnlewis).
isfictif(non,papefrancois).
isfictif(yes,jamesbond).
isfictif(non,juliesnyder).
isfictif(yes,moise).
isfictif(yes,mario).
isfictif(yes,laracroft).
isfictif(non,jkrowling).
isfictif(non,jacquesvilleneuve).
isfictif(non,cleopatre7).
isfictif(non,victorhugo).
isfictif(yes,jesus).
isfictif(non,eugeniebouchard).
isfictif(non,bradpitt).

isdead(yes,michaeljackson).
isdead(non,stephenharper).
isdead(yes,mozart).
isdead(non,michelgagnon).
isdead(non,blancheneige).
isdead(non,rafalnadal).
isdead(non,garfield).
isdead(non,micheldagenais).
isdead(non,johnlewis).
isdead(non,papefrancois).
isdead(non,jamesbond).
isdead(non,juliesnyder).
isdead(yes,moise).
isdead(non,mario).
isdead(non,laracroft).
isdead(non,jkrowling).
isdead(non,jacquesvilleneuve).
isdead(yes,cleopatre7).
isdead(yes,victorhugo).
isdead(non,jesus).
isdead(non,eugeniebouchard).
isdead(non,bradpitt).

isquebecois(non,michaeljackson).
isquebecois(non,stephenharper).
isquebecois(non,mozart).
isquebecois(yes,michelgagnon).
isquebecois(non,blancheneige).
isquebecois(non,rafalnadal).
isquebecois(non,garfield).
isquebecois(yes,micheldagenais).
isquebecois(non,johnlewis).
isquebecois(non,papefrancois).
isquebecois(non,jamesbond).
isquebecois(yes,juliesnyder).
isquebecois(non,moise).
isquebecois(non,mario).
isquebecois(non,laracroft).
isquebecois(non,jkrowling).
isquebecois(yes,jacquesvilleneuve).
isquebecois(non,cleopatre7).
isquebecois(non,victorhugo).
isquebecois(non,jesus).
isquebecois(yes,eugeniebouchard).
isquebecois(non,bradpitt).

issportif(non,michaeljackson).
issportif(non,stephenharper).
issportif(non,mozart).
issportif(non,michelgagnon).
issportif(non,blancheneige).
issportif(yes,rafalnadal).
issportif(non,garfield).
issportif(non,micheldagenais).
issportif(non,johnlewis).
issportif(non,papefrancois).
issportif(non,jamesbond).
issportif(non,juliesnyder).
issportif(non,moise).
issportif(yes,mario).
issportif(non,laracroft).
issportif(non,jkrowling).
issportif(yes,jacquesvilleneuve).
issportif(non,cleopatre7).
issportif(non,victorhugo).
issportif(non,jesus).
issportif(yes,eugeniebouchard).
issportif(non,bradpitt).

isamerican(yes,michaeljackson).
isamerican(non,stephenharper).
isamerican(non,mozart).
isamerican(non,michelgagnon).
isamerican(non,blancheneige).
isamerican(non,rafalnadal).
isamerican(yes,garfield).
isamerican(non,micheldagenais).
isamerican(yes,johnlewis).
isamerican(non,papefrancois).
isamerican(non,jamesbond).
isamerican(non,juliesnyder).
isamerican(non,moise).
isamerican(non,mario).
isamerican(yes,laracroft).
isamerican(non,jkrowling).
isamerican(non,jacquesvilleneuve).
isamerican(non,cleopatre7).
isamerican(non,victorhugo).
isamerican(non,jesus).
isamerican(non,eugeniebouchard).
isamerican(yes,bradpitt).

ispolitician(non,michaeljackson).
ispolitician(yes,stephenharper).
ispolitician(non,mozart).
ispolitician(non,michelgagnon).
ispolitician(non,blancheneige).
ispolitician(non,rafalnadal).
ispolitician(non,garfield).
ispolitician(non,micheldagenais).
ispolitician(yes,johnlewis).
ispolitician(non,papefrancois).
ispolitician(non,jamesbond).
ispolitician(non,juliesnyder).
ispolitician(non,moise).
ispolitician(non,mario).
ispolitician(non,laracroft).
ispolitician(non,jkrowling).
ispolitician(non,jacquesvilleneuve).
ispolitician(yes,cleopatre7).
ispolitician(non,victorhugo).
ispolitician(non,jesus).
ispolitician(non,eugeniebouchard).
ispolitician(non,bradpitt).

iswriter(non,michaeljackson).
iswriter(non,stephenharper).
iswriter(non,mozart).
iswriter(non,michelgagnon).
iswriter(non,blancheneige).
iswriter(non,rafalnadal).
iswriter(non,garfield).
iswriter(non,micheldagenais).
iswriter(non,johnlewis).
iswriter(non,papefrancois).
iswriter(non,jamesbond).
iswriter(non,juliesnyder).
iswriter(non,moise).
iswriter(non,mario).
iswriter(non,laracroft).
iswriter(yes,jkrowling).
iswriter(non,jacquesvilleneuve).
iswriter(non,cleopatre7).
iswriter(yes,victorhugo).
iswriter(non,jesus).
iswriter(non,eugeniebouchard).
iswriter(non,bradpitt).

isreligiousfigure(non,michaeljackson).
isreligiousfigure(non,stephenharper).
isreligiousfigure(non,mozart).
isreligiousfigure(non,michelgagnon).
isreligiousfigure(non,blancheneige).
isreligiousfigure(non,rafalnadal).
isreligiousfigure(non,garfield).
isreligiousfigure(non,micheldagenais).
isreligiousfigure(non,johnlewis).
isreligiousfigure(yes,papefrancois).
isreligiousfigure(non,jamesbond).
isreligiousfigure(non,juliesnyder).
isreligiousfigure(yes,moise).
isreligiousfigure(non,mario).
isreligiousfigure(non,laracroft).
isreligiousfigure(non,jkrowling).
isreligiousfigure(non,jacquesvilleneuve).
isreligiousfigure(non,cleopatre7).
isreligiousfigure(non,victorhugo).
isreligiousfigure(yes,jesus).
isreligiousfigure(non,eugeniebouchard).
isreligiousfigure(non,bradpitt).

isteachAI(non,michaeljackson).
isteachAI(non,stephenharper).
isteachAI(non,mozart).
isteachAI(yes,michelgagnon).
isteachAI(non,blancheneige).
isteachAI(non,rafalnadal).
isteachAI(non,garfield).
isteachAI(non,micheldagenais).
isteachAI(non,johnlewis).
isteachAI(non,papefrancois).
isteachAI(non,jamesbond).
isteachAI(non,juliesnyder).
isteachAI(non,moise).
isteachAI(non,mario).
isteachAI(non,laracroft).
isteachAI(non,jkrowling).
isteachAI(non,jacquesvilleneuve).
isteachAI(non,cleopatre7).
isteachAI(non,victorhugo).
isteachAI(non,jesus).
isteachAI(non,eugeniebouchard).
isteachAI(non,bradpitt).

questions([
[ishomme,'bruit'],
[isfictif,'nettoyer'],
%[isdead,'main'],
[isquebecois,'conteneur'],
[issportif,'info'],
[isamerican, 'america'],
[ispolitician,'info'],
[iswriter,'info'],
[isreligiousfigure, 'religion'],
[isteachAI, 'AI']]).

askQuestion([Pred,Question],Value,X):-
	call(Pred,Value,X).

getFirstQuestion([H|T],H,T).

findCollision(X,Y,Z):-findMatch(X,Y),findMatch(X,Z),Z\=Y. 

findMatch(X,Y):-questions(ListQuestions),
	iteration(X,Y,ListQuestions).

iteration([],Y,[]).

iteration([H|T],Y,ListQuestions):-
	getFirstQuestion(ListQuestions,Question,Rest),
	askQuestion(Question,H,Y),
	iteration(T,Y,Rest).

